import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const questions = [
  {
    label: 'What is PrepAI?',
    content:
      'PrepAI is a platform where you can prepare for your next job position with the help of AI. By completing activities and mock interviews, you will be ready.',
  },
  {
    label: 'How is the feedback generated?',
    content:
      'Feedback is generated by AI after each interview or exam. You will receive feedback on your answers, pointing out areas that need improvement, along with a score indicating how well you performed in the activity.',
  },
  {
    label: 'Is it free?',
    content:
      'PrepAI offers a free tier plan where you can explore all features. If you reach the free limits, you can upgrade to a premium plan.',
  },
  {
    label: 'What are paths?',
    content:
      'Paths guide you through what you need to know to be fully prepared for an interview. By reading key information and completing activities and projects, you will practice for your upcoming interview. All paths are created by AI and tailored to your job needs.',
  },
  {
    label: 'How are mock interviews structured?',
    content:
      'Mock interviews simulate real-life interview scenarios and are tailored to your selected job role. You will answer questions, receive instant feedback, and improve your skills with each session.',
  },
  {
    label: 'Can I track my progress?',
    content:
      'Yes, PrepAI tracks your progress across different paths, interviews, and exams. You can view your scores, completed activities, and areas where you need to improve.',
  },
];

export function Faq() {
  return (
    <Accordion type='single' collapsible className='w-full p-2 max-w-[900px]'>
      {questions.map((question, i) => (
        <AccordionItem key={i} value={`item-${i}`} className='mb-2 border-0'>
          <AccordionTrigger className='text-base lg:text-lg font-semibold px-6 text-start border-0'>
            {question.label}
          </AccordionTrigger>
          <AccordionContent className='text-base text-muted-foreground px-6'>
            {question.content}
          </AccordionContent>
        </AccordionItem>
      ))}
    </Accordion>
  );
}
